# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: df69d9c
_src_path: /Users/samvaughan/Code/spv-copier-template
copyright_date: '2023'
name: Sam Vaughan
project_description: Investigating calibration lamps for MAVIS using HECTOR data
project_name: MAVIS-calibration
